language: python
python:
  - 3.7

os: linux
sudo: required
cache: pip

before_install:
    - sudo apt-get install -y -q openmpi-bin libopenmpi-dev

install:
  - pip install pipenv
  - pipenv lock -r > requirements.txt
  - pip install -r requirements.txt

script:
  - python setup.py test
