language: python
python:
  - 3.6
  - 3.7

os: linux
sudo: required
cache: pip

install:
  - pip install pipenv
  - pipenv lock -r > requirements.txt
  - pip install -r requirements.txt

script:
  - python setup.py test
